/**
 * /lib/cursor-rules.ts
 * Generates .cursorrules content for each repo and pushes to GitHub.
 */

import { supabaseAdmin } from "@/lib/supabase"
import { callClaudeDraft } from "@/lib/claude"

interface RepoWithTasks {
  github_repo: string
  display_name: string | null
  business_id: string
  repo_type: string
}

const BUSINESS_CONTEXT: Record<string, string> = {
  swiftfi:         "SwiftFi is a crypto onramp app at swiftfi.com. Revenue-generating. Stack: Next.js, TypeScript, Vercel.",
  unbeatableloans: "UnbeatableLoans is a mortgage application platform at unbeatableloans.com. Early stage. Stack: Next.js, TypeScript, Vercel.",
  ollacart:        "OllaCart is a social shopping cart at ollacart.com. Integrates with Rye API. Stack: Next.js, TypeScript, Neo4j, Supabase, Vercel.",
  personal:        "Personal projects.",
}

const TECH_STACK: Record<string, string> = {
  landing: "Next.js App Router, TypeScript, Tailwind CSS, shadcn/ui, Vercel",
  app:     "Next.js App Router, TypeScript, Tailwind CSS, shadcn/ui, Supabase, Vercel",
}

/**
 * Generates .cursorrules file content for a given repo.
 * Pulls open tasks for the business from Supabase.
 */
export async function generateCursorRules(repo: RepoWithTasks): Promise<string> {
  // Pull top 5 open tasks for this business
  const { data: tasks } = await supabaseAdmin
    .from("tasks")
    .select("title, priority, status, category")
    .eq("business_id", repo.business_id)
    .in("status", ["todo", "in_progress", "blocked"])
    .order("priority", { ascending: true })
    .limit(5)

  const taskList = (tasks ?? [])
    .map((t) => `- [${t.status}] (${t.priority}) ${t.title}`)
    .join("\n") || "- No open tasks"

  // Pull recent open PRs from github_events
  const { data: prEvents } = await supabaseAdmin
    .from("github_events")
    .select("payload, claude_summary")
    .eq("github_event_type", "pull_request")
    .eq("github_event_action", "opened")
    .order("created_at", { ascending: false })
    .limit(3)

  const prList = (prEvents ?? [])
    .map((e) => {
      const pr = (e.payload as Record<string, unknown>)?.pull_request as Record<string, unknown> | undefined
      return `- PR #${pr?.number ?? "?"}: ${pr?.title ?? e.claude_summary ?? "(unknown)"}`
    })
    .join("\n") || "- No open PRs"

  const now = new Date().toISOString().split("T")[0]
  const businessCtx = BUSINESS_CONTEXT[repo.business_id] ?? repo.business_id
  const stackCtx = TECH_STACK[repo.repo_type] ?? TECH_STACK.app

  const content = await callClaudeDraft(
    `Generate a .cursorrules file for this repo:

Repo: ${repo.github_repo}
Display name: ${repo.display_name ?? repo.github_repo}
Business context: ${businessCtx}
Tech stack: ${stackCtx}
Date: ${now}

Current sprint priorities:
${taskList}

Active PRs:
${prList}

Format it exactly like this template (fill in the sections, keep the headers):

# ${repo.display_name ?? repo.github_repo}
# Auto-generated by Dash ERP. Updated: ${now}

## Business Context
[business description]

## Current Sprint Priorities
[task list]

## Tech Stack
[stack]

## Coding Standards
- TypeScript strict mode — no 'any' types
- Use existing component patterns in /components
- Follow existing API route patterns in /app/api
- pnpm for package management
- Test changes before committing to main

## Active PRs
[pr list]

## Notes
[any relevant context from the business/task situation]`,
    "You are generating a .cursorrules file for a Cursor IDE project. Be concise and practical. This file is read by Claude Code on every session.",
  )

  return content
}

/**
 * Commits .cursorrules content to a GitHub repo via the GitHub API.
 * Uses GITHUB_TOKEN env var.
 */
export async function commitCursorRules(
  githubRepo: string,
  content: string,
  branch = "main",
): Promise<{ ok: boolean; error?: string }> {
  const token = process.env.GITHUB_TOKEN
  if (!token) return { ok: false, error: "GITHUB_TOKEN not set" }

  const filePath = ".cursorrules"
  const apiBase = `https://api.github.com/repos/${githubRepo}/contents/${filePath}`

  // Get existing file SHA (needed for updates)
  let sha: string | undefined
  try {
    const existing = await fetch(`${apiBase}?ref=${branch}`, {
      headers: { Authorization: `Bearer ${token}`, Accept: "application/vnd.github+json" },
    })
    if (existing.ok) {
      const data = await existing.json() as { sha?: string }
      sha = data.sha
    }
  } catch {
    // File doesn't exist yet — that's fine
  }

  const encoded = Buffer.from(content, "utf8").toString("base64")
  const body: Record<string, unknown> = {
    message: `chore: update .cursorrules [skip ci]`,
    content: encoded,
    branch,
  }
  if (sha) body.sha = sha

  const res = await fetch(apiBase, {
    method: "PUT",
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  })

  if (!res.ok) {
    const err = await res.json().catch(() => ({})) as { message?: string }
    return { ok: false, error: err.message ?? `GitHub API ${res.status}` }
  }

  return { ok: true }
}

/**
 * Generates and commits TASKS.md to a GitHub repo.
 */
export async function commitTasksMd(
  githubRepo: string,
  businessId: string,
  branch = "main",
): Promise<{ ok: boolean; error?: string }> {
  const token = process.env.GITHUB_TOKEN
  if (!token) return { ok: false, error: "GITHUB_TOKEN not set" }

  const { data: tasks } = await supabaseAdmin
    .from("tasks")
    .select("title, priority, status, category, due_date")
    .eq("business_id", businessId)
    .eq("category", "dev")
    .not("status", "eq", "archived")
    .order("priority", { ascending: true })

  const bucket = (priority: string) =>
    priority === "urgent" ? "urgent" : priority === "high" ? "this_week" : "backlog"

  const urgent: string[] = []
  const thisWeek: string[] = []
  const backlog: string[] = []

  for (const t of tasks ?? []) {
    const line = `- [${t.status === "done" ? "x" : " "}] ${t.title}${t.due_date ? ` (due ${t.due_date})` : ""}`
    const b = bucket(t.priority)
    if (b === "urgent") urgent.push(line)
    else if (b === "this_week") thisWeek.push(line)
    else backlog.push(line)
  }

  const now = new Date().toISOString()
  const content = [
    `# Tasks — ${businessId}`,
    `Last synced: ${now}`,
    "",
    "## Urgent",
    ...(urgent.length ? urgent : ["- (none)"]),
    "",
    "## This Week",
    ...(thisWeek.length ? thisWeek : ["- (none)"]),
    "",
    "## Backlog",
    ...(backlog.length ? backlog : ["- (none)"]),
  ].join("\n")

  const filePath = "TASKS.md"
  const apiBase = `https://api.github.com/repos/${githubRepo}/contents/${filePath}`

  let sha: string | undefined
  try {
    const existing = await fetch(`${apiBase}?ref=${branch}`, {
      headers: { Authorization: `Bearer ${token}`, Accept: "application/vnd.github+json" },
    })
    if (existing.ok) {
      const data = await existing.json() as { sha?: string }
      sha = data.sha
    }
  } catch { /* new file */ }

  const body: Record<string, unknown> = {
    message: `chore: sync TASKS.md [skip ci]`,
    content: Buffer.from(content, "utf8").toString("base64"),
    branch,
  }
  if (sha) body.sha = sha

  const res = await fetch(apiBase, {
    method: "PUT",
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
    },
    body: JSON.stringify(body),
  })

  if (!res.ok) {
    const err = await res.json().catch(() => ({})) as { message?: string }
    return { ok: false, error: err.message ?? `GitHub API ${res.status}` }
  }

  return { ok: true }
}
